backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”

# If we use editorial_workflow, we cant have autotweet.
# This is because it creates a PR instead of committing directly to master so we cant read the commit message

# publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

display_url: https://www.amandabrookfield.co.uk

collections:
  - name: pages-and-announcements
    label: Pages & Announcements
    files:
      - file: src/pages/index.md
        label: Home
        name: home
        fields:
          - {label: Welcome Text, name: welcomeText, widget: text}
      - file: src/announcement/index.md
        label: Announcement
        name: announcement
        create: false
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {
              label: Button Text,
              name: buttonText,
              widget: string,
              required: false,
              default: '',
            }
          - {
              label: Button Link,
              name: buttonLink,
              widget: string,
              required: false,
              default: '',
            }
          - {
              label: Display Until,
              name: displayUntil,
              widget: datetime,
              required: false,
              default: '',
            }
          - {label: Disable Announcement?, name: isDisabled, widget: boolean}
      - file: src/pages/events/index.md
        label: Events
        name: events
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: events-page,
            }
          - {
              label: Events,
              name: events,
              widget: list,
              fields:
                [
                  {label: Title, name: title, widget: string},
                  {label: Date, name: date, widget: date},
                  {
                    label: "Time [eg '7pm']",
                    name: time,
                    widget: string,
                    required: false,
                    default: '',
                  },
                  {
                    label: Description,
                    name: description,
                    widget: text,
                    required: false,
                    default: '',
                  },
                ],
            }
  - name: blog
    label: Blog Posts
    folder: src/pages/blog
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: Template Key,
          name: templateKey,
          widget: hidden,
          default: blog-post,
        }
      - {label: Title, name: title, widget: string}
      - {label: Publish Date, name: date, widget: date}
      - {label: Body, name: body, widget: markdown}
      - {label: Tags, name: tags, widget: list, required: false}
  - name: articles
    label: Articles
    folder: src/pages/articles
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: Template Key,
          name: templateKey,
          widget: hidden,
          default: article-page,
        }
      - {label: Title, name: title, widget: string}
      - {label: Publish Date, name: date, widget: date}
      - {label: Body, name: body, widget: markdown}
  - name: short-stories
    label: Short Stories
    folder: src/pages/short-stories
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: Template Key,
          name: templateKey,
          widget: hidden,
          default: article-page,
        }
      - {label: Title, name: title, widget: string}
      - {label: Publish Date, name: date, widget: date}
      - {label: Body, name: body, widget: markdown}
  - name: books
    label: Books
    folder: src/pages/books
    fields:
      - {
          label: Template Key,
          name: templateKey,
          widget: hidden,
          default: book-page,
        }
      - {label: Book ID, name: bookId, widget: hidden}
      - {label: Path, name: path, widget: hidden}
      - {label: Title, name: title, widget: string}
      - {label: Body, name: body, widget: markdown}
      - {
          label: Reviews,
          name: reviews,
          widget: list,
          fields:
            [
              {label: Text, name: text, widget: text},
              {label: Reviewer, name: reviewer, widget: string},
            ],
        }
