name: Trigger Netlify Build
on:
  schedule:
    # Run every Sunday at midnight
    - cron: '00 00 * * 0'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5ead890ce0d61406bf3ed3f1
